In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")

In [3]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df['spam'] = df['Category'].apply(lambda x:1 if x=="spam" else 0)

In [6]:
df.shape

(5572, 3)

In [7]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.2)

In [10]:
X_train.shape

(4457,)

In [11]:
X_test.shape

(1115,)

In [12]:
type(X_train)

pandas.core.series.Series

In [13]:
X_train[:4]

4805    Er, hello, things didn‘t quite go to plan – is...
4311    Someone U know has asked our dating service 2 ...
1938    The fact that you're cleaning shows you know w...
2872    I actually did for the first time in a while. ...
Name: Message, dtype: object

In [14]:
y_train[:4]

4805    0
4311    1
1938    0
2872    0
Name: spam, dtype: int64

In [16]:
from sklearn.feature_extraction.text  import CountVectorizer

In [18]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [19]:
from sklearn.pipeline import Pipeline

In [20]:
clf = Pipeline([('Vectorizer', CountVectorizer()),('nb', MultinomialNB())])

In [22]:
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       987
           1       0.97      0.93      0.95       128

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115